/**
 * Browser-safe syllable counting and stress detection.
 *
 * Uses a pre-baked JSON dictionary derived from CMUdict (generated by
 * scripts/build-stress-dict.cjs) for accurate stress patterns, with a
 * heuristic fallback for unknown words.
 *
 * NOTE: All regexes are created inside functions, never at module level with
 * the `g` flag, to avoid shared mutable lastIndex state.
 */

import stressDict from './stress-dict.json';

function countWordSyllables(word: string): number {
  if (!word) return 0;
  const clean = word.toLowerCase().replace(/[^a-z]/g, '');
  if (!clean) return 0;

  const groups = clean.match(/[aeiouy]+/gi);
  if (!groups) return 0;

  let count = groups.length;
  if (/e$/i.test(clean) && count > 1) count--;
  if (/[^aeiouy]le$/i.test(clean)) count++;

  return Math.max(1, count);
}

/**
 * Count syllables for a line of text using heuristics only.
 * Returns 0 for empty/punctuation-only input.
 */
export function countSyllablesBrowser(line: string): number {
  if (!line || !line.trim()) return 0;
  const words = line.trim().split(/\s+/).filter(w => /[a-zA-Z]/.test(w));
  if (!words.length) return 0;
  return words.reduce((sum, w) => sum + countWordSyllables(w), 0);
}

/**
 * Per-syllable range within the original line string, with stress type.
 * `start`/`end` are offsets into `line` covering the vowel nucleus of
 * that syllable. `stressed` follows simple heuristics:
 *   - 1-syllable word  → stressed (context-dependent in real poetry, but
 *     we default to stressed so single-syllable words get "/" not "^")
 *   - multi-syllable   → stress index determined by getPrimaryStressIndex
 *     (penultimate by default, with suffix overrides)
 */
export interface SyllableRange {
  start: number;
  end: number;
  stressed: boolean;
}

/**
 * Returns the 0-based index of the primary stressed syllable for a cleaned
 * lowercase word (no punctuation), given its syllable count.
 *
 * Rules (simplified English stress heuristics):
 *  1-syllable words  → index 0 (always stressed)
 *  2-syllable words  → index 0 (initial stress is the common default)
 *  3+ syllable words → penultimate (second-to-last) by default, with:
 *    - Antepenultimate (-ity, -ical, -ily, -ically, -ify, -ible, -able,
 *                       -ulous, -ulous, -eous, -ious, -uous) → n-3
 *    - Final stress   (-eer, -ique, -esque, -ette, -oon, -ade, -ain,
 *                      -ese, -ense, -ive suffix on 2+ syl) → last
 */
function getPrimaryStressIndex(clean: string, syllableCount: number): number {
  if (syllableCount <= 1) return 0;
  if (syllableCount === 2) {
    // Common 2-syllable words with final stress (French/Latin origin)
    if (/(?:oon|ain|ade|ese|eer|ique|ette|ense)$/.test(clean)) return 1;
    return 0;
  }
  // 3+ syllables
  const last = syllableCount - 1;
  const penult = syllableCount - 2;
  const antepenult = syllableCount - 3;

  // Final stress suffixes
  if (/(?:eer|ique|esque|ette|oon|ade|ain|ese|ense)$/.test(clean)) return last;
  // Antepenultimate stress suffixes
  if (/(?:ity|ical|ically|ify|ible|able|ulous|eous|ious|uous|ily|ic)$/.test(clean)) {
    return Math.max(0, antepenult);
  }
  // Default: penultimate
  return Math.max(0, penult);
}

export function getSyllableRanges(line: string): SyllableRange[] {
  if (!line) return [];
  try {
    const ranges: SyllableRange[] = [];
    let cursor = 0;

    while (cursor < line.length) {
      // Skip whitespace
      if (/\s/.test(line[cursor])) { cursor++; continue; }

      // Find end of token
      let tokenEnd = cursor;
      while (tokenEnd < line.length && !/\s/.test(line[tokenEnd])) tokenEnd++;

      const token = line.slice(cursor, tokenEnd);

      if (/[a-zA-Z]/.test(token)) {
        const clean = token.toLowerCase().replace(/[^a-z]/g, '');

        // Find all vowel groups (= syllable nuclei) in this token
        const vowelRe = /[aeiouyAEIOUY]+/g;
        const groups: Array<{ index: number; length: number }> = [];
        let m: RegExpExecArray | null;
        while ((m = vowelRe.exec(token)) !== null) {
          groups.push({ index: m.index, length: m[0].length });
        }

        // Determine stress pattern — dictionary first, heuristic fallback
        const dictPattern: string | undefined = (stressDict as Record<string, string>)[clean];

        let stressedIndex: number;
        let syllableCount: number;

        if (dictPattern) {
          // Dictionary: pattern length = syllable count, 'S' = stressed
          syllableCount = Math.min(dictPattern.length, groups.length);
          stressedIndex = dictPattern.indexOf('S');
          if (stressedIndex === -1 || stressedIndex >= syllableCount) stressedIndex = 0;
        } else {
          // Heuristic fallback
          syllableCount = groups.length;
          if (/e$/i.test(clean) && syllableCount > 1) syllableCount--;
          stressedIndex = getPrimaryStressIndex(clean, syllableCount);
        }

        const activeGroups = groups.slice(0, syllableCount);
        activeGroups.forEach((g, i) => {
          ranges.push({
            start: cursor + g.index,
            end: cursor + g.index + g.length,
            stressed: i === stressedIndex,
          });
        });
      }

      cursor = tokenEnd;
    }

    return ranges;
  } catch {
    return [];
  }
}

/** @deprecated Use getSyllableRanges instead */
export function getStressedRanges(line: string): SyllableRange[] {
  return getSyllableRanges(line).filter(r => r.stressed);
}
